[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/", "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"
monad_mainnet = "${MONAD_MAINNET_RPC_URL}"

[profile.monad_testnet]
eth_rpc_url = "${MONAD_TESTNET_RPC_URL}"
chain_id = 10143

[etherscan]
monad_testnet = { key = "${SCAN_API_KEY}", chain = 10143, url = "https://testnet.monadscan.com/api" }
